#include "package/package.cuh"

//	Utilisation:
//		./test_package


/*	

One file generated by run.py 
All is make with pseudo_random with seed=0

1 data batch for all

[for model in py_models]
	shuffle batch #save new data

	/// test juste model forward no sets
	set_input	#check
	forward		#check

	///	test with sets
	[for score in scores]
		[for opti in optimizers]
			[for echope in min_loops[opti]]	//sgd a besoin que d'un seul echope pour performer, momentum a un moment, donc au moins 2 loops
				set_input
				null_grad	#check
				forward		#check
				score.dloss	#check
				backward 	#check
				opti.opti 	#check

				shuffle batch #save new data
			[end]
		[end]	
	[end]
	
	[for gtic in gtics]
		set_input
		null_grad	#check
		forward		#check
		score.loss	#check
		gtic.opti 	#check

		shuffle batch
	[end]
[end]
*/

int main(int argc, char ** argv) {
	system("python3 -m programs.test_package.run");

	for (uint model=0; model < models; model++) {

	};
};